ColoradoChristianUniversity/CIS-230-SP24

Ethics/SydneyCrowder/Week01.md
Final Draft for week 1 ethical issue.
=> Week 1 Ethics- Sydney Crowder

Ethics/SethFreeman/Week01 Ethics
This is my submission for the ethics assignment for week 1.
=> Week01 Ethics - Seth Freeman

Ethics/MasonLink/Week01.md
Here is my Week 01 Ethics Assignment pull request. Thanks!
=> Week 01 Ethics, Mason Link

Ethics/IsraelMunguia/Week01.MD
=> Week 1 Ethics - Israel Munguia

Ethics/GabeWassmer/Week01.md
=> Week 1 Ethics - Gabe Wassmer

Ethics/TimValley/Week01.md
Hi Professor Nixon, you are the best!
=> Week 1 Ethics - Tim Valley

Ethics/Alex Baxter/Week01.md
=> EthicsWeek01-AlexBaxter

Ethics/JaxsonMcAdoo/Week02.md
Hello Professor Nixon, I have completed the ethics asssignment for week 2.
=> Week 2 Ethics - Jaxson McAdoo

Ethics/GabeWassmer/Week02.md
=> Week 2 Ethics - Gabe Wassmer

Ethics/AlexBaxter/Week03.md
This is week 3 done :) 
Hopefully this works this time
=> Week 3 Ethics - Alex Baxter

Ethics/SydneyCrowder/Week03.md
=> Week 3 Ethics -Sydney Crowder

Ethics/EvanDayton/Week03.md
=> Ethics03-EvanDayton

Ethics/Jewels Marlewski/W04 Ethics
=> Marlewski, Jewels Ethics W04

Ethics/IsraelMunguia/Week03.MD
=> Week03Ethics -Israel Munguia

Ethics/SydneyCrowder/Week04.md
=> SydneyCrowderWeek04

Ethics/EvanDayton/week04 - ethics
Final submission - week04 ethics
=> Final - week04

Ethics/MasonLink/Week05.md
Here is my week 05 ethics. Thanks!
=> LinkMason-Ethics05

Ethics/IsraelMunguia/Week02.MD
=> Week2 Final

Ethics/MasonLink/Week02.md
Here is my Ethics02 assignment. Thanks!
=> LinkMason-Ethics02

Ethics/SydneyCrowder/Week02.md
=> Week 2 Ethics

Ethics/EvanDayton/week02.md
Final submission for week 2 ethics assignment.
=> Week 2 Ethics - EvanDayton

Ethics/MasonLink/Week03.md
=> LinkMason-Ethics03

Ethics/MasonLink/Week04.md
Here is my week 4 ethics assignment. Thanks!
=> LinkMason-Ethics04

Ethics/EvanDayton/week05 - ethics.md
=> week05 - final

Ethics/Jewels Marlewski/Week05.md
Completed W05 Ethics - Late Submit due to Extension for Funeral
=> Week05 Ethics

Ethics/GabeWassmer/Week05.md
=> Commit Draft #1

Ethics/EvanDayton/week06.md
=> week6 - final

Ethics/SydneyCrowder/Week06.md
=> EthicsWeek06-SydneyCrowder

Ethics/MasonLink/Week06.md
=> LinkMason-EthicsWeek06

Week 1 Ethics, Micah Bissell/MicahBissell/Week06.md
=> EthicsWeek06-MicahBissell

Ethics/GabeWassmer/Week06.md
=> Final Commit

Ethics/Jewels Marlewski/W06 Ethics
=> Final Ethics

Ethics/Alex Baxter/Week07.md
=> Ethics week 7 alex baxter

Ethics/SydneyCrowder/Week07.md
=> Ethics07-SydneyCrowder

Ethics/EvanDayton/week07.md
final commit for ethics week 7
=> Final - Ethics 7

Ethics/MasonLink/Week07.md
=> LinkMason-EthicsWeek07

Week 1 Ethics, Micah Bissell/MicahBissell/Week07.md, Week 1 Ethics, Micah Bissell/MicahBissell/Week08.md, Week 1 Ethics, Micah Bissell/Week05.md
=> Week08Ethics-MicahBissell

Ethics/SydneyCrowder/Week08.md
=> EthicsWeek08-SydneyCrowder

Ethics/EvanDayton/week08.md
final commit for week 8 ethics
=> week8 - final

Ethics/MasonLink/Week08.md
=> Ethics08-LinkMason

Ethics/Jewels Marlewski/W08 Ethics.md
=> Marlewski Jewels Week08 ethics

Ethics/IsraelMunguia/Week08.MD
=> EthicsWeek08 - Diego Munguia

Ethics/GabeWassmer/Week08.md
=> EthicsWk8-GabeWassmer

Ethics/Alex Baxter/week09.md
this is some dang ethical stuff right here
=> week 09 done _ alex baxter

Ethics/EvanDayton/week09.md
final commit for week 9 ethics
=> final - ethics9

Ethics/SydneyCrowder/Week09.md
=> EthicsWeek09-SydneyCrowder

Ethics/MasonLink/Week09.md
=> LinkMason-Week09

Ethics/GabeWassmer/Week09.md
=> EthicsWk9-Pull Request

Ethics/Alex Baxter/Week11.md
=> Week11-Ethics-Alex-Baxter

Ethics/Jewels Marlewski/W11.md
=> W11 ethics marlewski jewels

Ethics/GabeWassmer/Week11.md
=> Pull-Ethics11-Wassmer

Ethics/SydneyCrowder/Week11.md
=> SydneyCrowder-Ethics-Week11

Ethics/EvanDayton/week11.md
=> week11 - done

Ethics/MicahBissell/Week12.md
=> EthicsWeek12-MicahBissell

Ethics/GabeWassmer/Week12.md
Pull request for week 12 ethical response.
=> EthicsWk12-GabeWassmer

Ethics/Jewels Marlewski/W12 Ethics.md
=> Marlewski, Jewels w12Ethics

Ethics/MicahBissell/Week13.md
=> Week 13 Ethics

Ethics/SydneyCrowder/Week13.md
=> EthicsWeek13-SydneyCrowder

Ethics/MasonLink/Week09.md, Ethics/MasonLink/Week13.md
=> LinkMason-EthicsWeek13

Ethics/Jewels Marlewski/W13 Ethics.md
=> Marlewski, Jewels W13 Ethics

Ethics/JaxsonMcAdoo/Week13.md
I've completed the Ethics assignment for week 13, hopefully I did it right this time.
=> Ethics-Week-13

Ethics/GabeWassmer/Week13.md
Ethics pull request for week 13.
=> PullEthicsWk13-GabeWassmer

Ethics/Alex Baxter/week14.md
=> Ethics-14-Baxter

Ethics/MicahBissell/Week14.md
=> Week 14 Ethics Bissell

Ethics/SydneyCrowder/Week14.md
=> Ethics-Week14-SydneyCrowder

Ethics/MasonLink/Week14.md
=> LinkMason-EthicsWeek14

Ethics/JaxsonMcAdoo/Week14.md
I have completed the ethics assignment for this week
=> Ethics Complete

Ethics/GabeWassmer/Week14.md
=> PullWk14-GabeWassmer

Ethics/Alex Baxter/week15.md
=> Week15-Alex-Baxter-Done

Ethics/GabeWassmer/Week15.md
=> PullEthicsWk15-GabeWassmer

Ethics/MicahBissell/Week15.md
=> Week 15 Ethics

Ethics/MasonLink/Week15.md
=> LinkMason-Ethics15

Ethics/SydneyCrowder/Week15.md
=> EthicsWeek-15-SydneyCrowder
